#!/bin/bash
# Runs as an Xcode "Run Script" build phase (and may be called from ci_post_clone).
# When SUPABASE_URL + SUPABASE_ANON_KEY are in the environment (Xcode Cloud workflow),
# writes EchoMemories/GeneratedSupabaseConfig.swift with base64-encoded values so we do
# not depend on Info.plist $(VAR) expansion from xcconfig (often breaks on Cloud archives).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/EchoMemories/GeneratedSupabaseConfig.swift"

env_strip() { printf '%s' "${1:-}" | tr -d '\r'; }
SUPABASE_URL="$(env_strip "${SUPABASE_URL:-}")"
SUPABASE_ANON_KEY="$(env_strip "${SUPABASE_ANON_KEY:-}")"
PUBLIC_SHARE_BASE_URL="$(env_strip "${PUBLIC_SHARE_BASE_URL:-}")"

b64() { printf '%s' "$1" | base64 | tr -d '\n'; }

write_file() {
  cat > "$OUT" <<EOF
// AUTO-GENERATED by ci_scripts/write_generated_supabase_swift.sh — do not edit by hand.
enum GeneratedSupabaseConfig {
    static let supabaseURLB64 = "$1"
    static let supabaseAnonKeyB64 = "$2"
    static let publicShareBaseURLB64 = "$3"
}
EOF
}

if [[ -n "$SUPABASE_URL" && -n "$SUPABASE_ANON_KEY" ]]; then
  write_file "$(b64 "$SUPABASE_URL")" "$(b64 "$SUPABASE_ANON_KEY")" "$(b64 "$PUBLIC_SHARE_BASE_URL")"
  echo "write_generated_supabase_swift: wrote embedded secrets from environment."
else
  write_file "" "" ""
  echo "write_generated_supabase_swift: cleared embeds (use Info.plist / Secrets.xcconfig)."
fi
