// AUTO-GENERATED by ci_scripts/write_generated_supabase_swift.sh — do not edit by hand.
enum GeneratedSupabaseConfig {
    static let supabaseURLB64 = ""
    static let supabaseAnonKeyB64 = ""
    static let publicShareBaseURLB64 = ""
}
